### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by YoussefAKQ** [jotaaloud/portfolio#2]
Creo que deberías añadir un hover al menú, quedaría más intuitivo.

**Comment by jotaaloud** [comment]
Verdad! Tengo que actualizar el portfolio, meteré eso y más cosas cuando termine el curso en el que estoy.
Muchas gracias!

**Comment by codejovz** [comment]
Verdad! Tengo que actualizar el portfolio, meteré eso y más cosas cuando termine el curso en el que estoy.
Muchas gracias!
